#!/bin/sh
set -e

SNAPSHOTTER_CONF="/etc/btrfs-snapshotter/config.toml"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${SNAPSHOTTER_CONF} ]; then
        rm ${SNAPSHOTTER_CONF}
    fi
    ;;
esac

#DEBHELPER#
